### ISSUE TITLE
Android: Bluetooth Manager instance issue

### ISSUE THREAD

**Issue by FabioGiulietti** [Connecthings/sdk-tutorial#1]
When the user tap the notification for ask bluetooth enabling, if the application was killed, then the app crash:

> Fatal Exception: java.lang.IllegalAccessError: Try to access to the BluetoothManager instance while it has not been initialized
       at com.connecthings.connectplace.common.utils.bluetooth.BluetoothManager.getInstance(SourceFile:70)
       at com.connecthings.connectplace.common.utils.bluetooth.GrantBackgroundPermissionReceiver.onReceive(SourceFile:18)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Library version:

> implementation('com.connecthings.adtag:android-adtag-beacon:3.0.2')

**Comment by opsct** [comment]
Thank you for the report.

We can't reproduce it unless the AdtagInitializer is not initialized in the Application as described in the [5 minutes quickstart tutorial](https://docs.connecthings.com/3.0/android/5-minutes-quickstart-beacons.html).

We invite you to check your code and to contact your Connecthings' account manager for futher support.
